### ISSUE TITLE
更新色彩数据文件

### ISSUE THREAD

**Issue by WenryXu** [yurenio/nippon-v2#1]
使用新的色彩数据文件，参照：

https://github.com/yurenio/nippon

期望做成全局数据

**Comment by HuiruDong** [comment]
就是把数据变成全局的呗？

**Comment by WenryXu** [comment]
是哇

**Comment by HuiruDong** [comment]
数据中少了两个 `nameColor` 吧，就是颜色最浅的那两个

**Comment by HuiruDong** [comment]
给补上了~位置在 id 为 233 和 234 的位置上
