### ISSUE TITLE
收藏

### ISSUE THREAD

**Issue by WenryXu** [yurenio/nippon-v2#4]
增加「标为收藏」和「取消收藏」功能，并在首页提供收藏列表

**Comment by HuiruDong** [comment]
请产品和 UI 一起来和我讨论一下具体是啥样的。

**Comment by WenryXu** [comment]
试过了，localstorage 写不出来……

**Comment by WenryXu** [comment]
https://github.com/yurenio/nippon-v2/commit/9df48064b4b5984b98be0022a03f3e6b140b1757 里面写了 `list-name` 的样式。

当不存在收藏的颜色时：

![image](https://user-images.githubusercontent.com/3060186/46414403-9d4cbe00-c755-11e8-994b-2c99c8b12cd9.png)

当存在收藏的颜色时：

![image](https://user-images.githubusercontent.com/3060186/46414696-42679680-c756-11e8-8e02-0e153ad29f3c.png)

收藏的颜色根据收藏顺序倒序排列，即从新到旧排列

**Comment by WenryXu** [comment]
已有分支 `wenryxu/4`
